name: routinex
description: "A new Flutter project."
publish_to: "none"
version: 0.1.3+4

environment:
  sdk: ^3.9.0

dependencies:
  awesome_notifications: ^0.10.1
  awesome_notifications_core: ^0.10.1
  cloud_firestore: ^6.1.3
  firebase_auth: ^6.2.0
  firebase_core: ^4.5.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^20.1.0
  google_sign_in: ^7.2.0
  intl: ^0.20.2
  permission_handler: ^12.0.1
dev_dependencies:
  fl_chart: ^0.66.0
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.0.5
  table_calendar: ^3.0.9

flutter:
  uses-material-design: true
  assets:
    - assets/logo/routineX_logo.png
    - assets/logo/full_logo.png
    - assets/logo/

flutter_icons:
  android: true
  ios: true
  image_path: assets/logo/routineX_logo.png
